### ISSUE TITLE
Video or keyboard animation stops

### ISSUE THREAD

**Issue by salihmarangoz** [salihmarangoz/system_tray_extensions#23]
Terminal output:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/salih/.system_tray_extensions/modules/FullRgbKeyboard/main.py", line 191, in video_function
    self.apply_voltmap(voltmap)
  File "/home/salih/.system_tray_extensions/modules/FullRgbKeyboard/main.py", line 368, in apply_voltmap
    self.ite.set_key_colors(self.voltmap_to_itemap(voltmap))
  File "/home/salih/.system_tray_extensions/ste_env/lib/python3.8/site-packages/ite8291r3_ctl/ite8291r3.py", line 275, in set_key_colors
    self.__set_row_index(row)
  File "/home/salih/.system_tray_extensions/ste_env/lib/python3.8/site-packages/ite8291r3_ctl/ite8291r3.py", line 185, in __set_row_index
    self.__send_ctrl(commands.SET_ROW_INDEX, 0x00, row_idx)
  File "/home/salih/.system_tray_extensions/ste_env/lib/python3.8/site-packages/ite8291r3_ctl/ite8291r3.py", line 157, in __send_ctrl
    self.channel.ctrl_transfer(
  File "/home/salih/.system_tray_extensions/ste_env/lib/python3.8/site-packages/ite8291r3_ctl/ite8291r3.py", line 284, in ctrl_transfer
    return self.dev.ctrl_transfer(*args, **kwargs)
  File "/home/salih/.system_tray_extensions/ste_env/lib/python3.8/site-packages/usb/core.py", line 1082, in ctrl_transfer
    ret = self._ctx.backend.ctrl_transfer(
  File "/home/salih/.system_tray_extensions/ste_env/lib/python3.8/site-packages/usb/backend/libusb1.py", line 893, in ctrl_transfer
    ret = _check(self.lib.libusb_control_transfer(
  File "/home/salih/.system_tray_extensions/ste_env/lib/python3.8/site-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 110] Operation timed out
```

**Comment by salihmarangoz** [comment]
Problem can be solved via disabling tdp package.
